remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

title: "Henry Goodman"
description: "Full-Stack Software Engineer"
baseurl: ""
url: "https://henrygoodman.github.io" 

# Social links
twitter_username: henrygoodman_dev
github_username: henrygoodman
linkedin_username: henry-goodman-9b7383225

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter_opts:
    default_lang: "plaintext"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

defaults:
  - scope:
      path: ""
    values:
      layout: default

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks for blog posts
permalink: /:year/:month/:day/:title/